defaults: ../../diffusion_grpo_qwen_image.yaml
grpo:
  max_num_steps: 50
  val_period: 25
  val_at_start: true
  max_val_samples: 16
checkpointing:
  checkpoint_dir: results/grpo-qwen-image-1n8g-dp8-lora
logger:
  log_dir: logs/grpo-qwen-image-1n8g-dp8-lora
  num_val_samples_to_print: 8
  wandb:
    name: grpo-qwen-image-1n8g-dp8-lora
